version: '3'

services:
  redis-master:
    container_name: "redis-master"
    image: redis:latest
    hostname: redis-master
    command: redis-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6379:6379"
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-master

  redis-slave1:
    container_name: "redis-slave1"
    hostname: redis-slave1
    image: redis:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6380:6379"
    command: redis-server /etc/redis/redis.conf 
    volumes:
      - ./configSentinel/redis-slave:/etc/redis
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-slave1

  redis-slave2:
    container_name: "redis-slave2"
    hostname: redis-slave2
    image: redis:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6381:6379"
    command: redis-server /etc/redis/redis.conf 
    volumes:
      - ./configSentinel/redis-slave:/etc/redis
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-slave2

  redis-sentinel1:
    container_name: "redis-sentinel1"
    hostname: redis-sentinel1
    image: redis:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: redis-server /etc/redis/redis.conf --sentinel
    volumes:
      - ./configSentinel/redis-sentinel:/etc/redis
    ports:
      - "5000:5000"
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-sentinel1

  redis-sentinel2:
    container_name: "redis-sentinel2"
    hostname: redis-sentinel2
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis:latest
    command: redis-server /etc/redis/redis.conf --sentinel
    volumes:
      - ./configSentinel/redis-sentinel:/etc/redis
    ports:
      - "5001:5001"
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-sentinel2

  redis-sentinel3:
    container_name: "redis-sentinel3"
    hostname: redis-sentinel3
    build:
      context: .
      dockerfile: ./Dockerfile
    image: redis:latest
    command: redis-server /etc/redis/redis.conf --sentinel
    volumes:
      - ./configSentinel/redis-sentinel:/etc/redis
    ports:
      - "5002:5002"
    networks:
      isolutionz-network-redis:
        aliases:
          - redis-sentinel3

networks:
  isolutionz-network-redis:
